### ISSUE TITLE
Bot won't start

### ISSUE THREAD

**Issue by imnato2** [adekmaulana/aioaria2-mirror-bot#47]
Step to reproduce:
Done the following step on deploying to heroku, filled all the config vars but ended with this

2021-10-01T11:09:27.081944+00:00 heroku[aioaria2-mirror-bot.1]: Starting process with command `bot`
2021-10-01T11:09:27.790905+00:00 heroku[aioaria2-mirror-bot.1]: State changed from starting to up
2021-10-01T11:09:35.251747+00:00 app[aioaria2-mirror-bot.1]:   INFO     |  launch       |  Loading code
2021-10-01T11:09:35.260178+00:00 app[aioaria2-mirror-bot.1]:   INFO     |  launch       |  Using uvloop event loop
2021-10-01T11:09:35.260210+00:00 app[aioaria2-mirror-bot.1]:   INFO     |  launch       |  Initializing bot
2021-10-01T11:09:35.266730+00:00 app[aioaria2-mirror-bot.1]:   ERROR    |  asyncio      |  Task exception was never retrieved
2021-10-01T11:09:35.266733+00:00 app[aioaria2-mirror-bot.1]: future: <Task finished name='Task-1' coro=<run.<locals>.new_coro() done, defined at /opt/venv/lib/python3.9/site-packages/aiorun.py:221> exception=JSONDecodeError('Expecting value: line 1 column 1 (char 0)')>
2021-10-01T11:09:35.266733+00:00 app[aioaria2-mirror-bot.1]: Traceback (most recent call last):
2021-10-01T11:09:35.266734+00:00 app[aioaria2-mirror-bot.1]:   File "/opt/venv/lib/python3.9/site-packages/aiorun.py", line 231, in new_coro
2021-10-01T11:09:35.266735+00:00 app[aioaria2-mirror-bot.1]:     await coro
2021-10-01T11:09:35.266736+00:00 app[aioaria2-mirror-bot.1]:   File "/opt/venv/lib/python3.9/site-packages/bot/core/bot.py", line 50, in init_and_run
2021-10-01T11:09:35.266737+00:00 app[aioaria2-mirror-bot.1]:     bot = cls()
2021-10-01T11:09:35.266737+00:00 app[aioaria2-mirror-bot.1]:   File "/opt/venv/lib/python3.9/site-packages/bot/core/bot.py", line 35, in __init__
2021-10-01T11:09:35.267193+00:00 app[aioaria2-mirror-bot.1]:     super().__init__()
2021-10-01T11:09:35.267195+00:00 app[aioaria2-mirror-bot.1]:   File "/opt/venv/lib/python3.9/site-packages/bot/core/telegram_bot.py", line 51, in __init__
2021-10-01T11:09:35.267195+00:00 app[aioaria2-mirror-bot.1]:     self.config = util.config.TelegramConfig()
2021-10-01T11:09:35.267195+00:00 app[aioaria2-mirror-bot.1]:   File "/opt/venv/lib/python3.9/site-packages/bot/util/config.py", line 44, in __init__
2021-10-01T11:09:35.267196+00:00 app[aioaria2-mirror-bot.1]:     value = json.loads(value)
2021-10-01T11:09:35.267196+00:00 app[aioaria2-mirror-bot.1]:   File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
2021-10-01T11:09:35.267196+00:00 app[aioaria2-mirror-bot.1]:     return _default_decoder.decode(s)
2021-10-01T11:09:35.267197+00:00 app[aioaria2-mirror-bot.1]:   File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
2021-10-01T11:09:35.267197+00:00 app[aioaria2-mirror-bot.1]:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
2021-10-01T11:09:35.267197+00:00 app[aioaria2-mirror-bot.1]:   File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
2021-10-01T11:09:35.267198+00:00 app[aioaria2-mirror-bot.1]:     raise JSONDecodeError("Expecting value", s, err.value) from None
2021-10-01T11:09:35.267198+00:00 app[aioaria2-mirror-bot.1]: json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-10-01T11:09:35.942142+00:00 heroku[aioaria2-mirror-bot.1]: Process exited with status 0
2021-10-01T11:09:36.046023+00:00 heroku[aioaria2-mirror-bot.1]: State changed from up to crashed

**Comment by imnato2** [comment]
Also can you sent me DB_URI string example? i think i'm putting invalid uri

DB_URI = `mongodb+srv://user:password@mongos0.example.com/DBname?retryWrites=true&w=majority`
