### ISSUE TITLE
mega command is broken

### ISSUE THREAD

**Issue by sweetcock69** [adekmaulana/aioaria2-mirror-bot#61]
`⚠️ Error executing command:
Traceback (most recent call last):
  File "/opt/venv/lib/python3.9/site-packages/bot/core/command_dispatcher.py", line 150, in on_command
    ret = await cmd.func(ctx)
  File "/opt/venv/lib/python3.9/site-packages/bot/plugins/mega.py", line 45, in cmd_mega
    uri = ctx.msg.reply_to_message.text or ctx.input
AttributeError: 'NoneType' object has no attribute 'text'`

**Comment by adekmaulana** [comment]
Thanks, will look into it when i have time
